version: '3.8'

services:
  plate-recognition:
    build: .
    ports:
      - "5000:5000"
      - "8000:8000"
    environment:
      - ENVIRONMENT=production
      - ENABLE_GPU=false
    volumes:
      - ./data:/app/data
      - ./models:/app/models
      - ./logs:/app/logs
      - ./web/static/uploads:/app/web/static/uploads
    restart: unless-stopped
    
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./web/static:/var/www/static
    depends_on:
      - plate-recognition
    restart: unless-stopped
